### ISSUE TITLE
Link Update in readme.md

### ISSUE THREAD

**Issue by gingebaker** [yellowled/pw-lang-de#44]
Hi
Just noticed that the Link in the readme.md for the DEV version
```
For use with a **dev** version, [see here](https://github.com/Manfred62/pw-lang-de-dev).
```
goes to:
https://github.com/Manfred62/pw-lang-de-dev
perhaps it would be better to go here:
https://github.com/Manfred62/pw-lang-de-devns

regards, tom

**Comment by yellowled** [comment]
Fixed in 599b2521ee48d66d73dd7c9999822476207dbf4d, thx.
